apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-user-frontend
  namespace: development
  labels:
    name: kwetter-user-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwetter-user-frontend
  template:
    metadata:
      labels:
        app: kwetter-user-frontend
        environment: development
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: secret-volume
        secret:
           secretName: nginx-certs-keys 
      - name: configmap-volume
        configMap:
          name: nginxconfigmap 
      containers:
      - name: kwetter-user-frontend
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        imagePullPolicy: Always
        image: mixampo.azurecr.io/repository-kwetter-user-frontend:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "125m"
        ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: kwetter-user-frontend
  namespace: development
  labels:
    name: kwetter-user-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 31443
  selector:
    app: kwetter-user-frontend
    environment: development
